name: Pages

on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4

    - name: yarn install
      run: yarn install

    - name: yarn run deploy
      run: yarn run deploy
